const mockData = {
    key: "123",
    code: "123",
    name: "Demo 1",
    assetTypeId: "Type 1",
    assetGroupId: "Group 1",
    note: "",
    unit: "",
    associatedAsset: ["Group 1", "Group 2"],
    siteId: "Site 1",
    status: "In Use",
    owner: "abc",
    supplierId: "aaa",
    purchaseDate: "2020-07-17",
    manufacturerId: "qqq",
    price: "120000",
    warranty: "12",
    cMark: "",
    iMark: "",
    aMark: "",
    note2: "",
    assignDateStart: "2020-07-17",
    assignDateEnd: "2020-07-17",
};

export default mockData;
