const mockData = [
    {
        key: "123123",
        code: "123123",
        name: "Test 1",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 1,
        c: '',
        i: 3,
        a: 5
    },
    {
        key: "456456",
        code: "456456",
        name: "Test 4",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 1,
        c: 2,
        i: 3,
        a: ''
    },
    {
        key: "789789",
        code: "789789",
        name: "Test 2",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 0,
        c: 2,
        i: 3,
        a: 5
    },
    {
        key: "112233",
        code: "112233",
        name: "Test 3",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 0,
        c: 2,
        i: 3,
        a: 5
    },
    {
        key: "112233",
        code: "112233",
        name: "Test 3",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 0,
        c: 2,
        i: 3,
        a: 1
    },
    {
        key: "112233",
        code: "112233",
        name: "Test 3",
        type: "Infomation Asset",
        group: "Infomation Asset",
        status: "In Use",
        owner: "",
        site: "",
        overdue: 0,
        c: 2,
        i: 3,
        a: 1
    },
]

export default mockData;